# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    
