# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160329_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StuGroup',
            new_name='ProjectGroup',
        ),
    ]
