# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('project_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project')),
                ('status', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(verbose_name='created on')),
                ('updated_date', models.DateTimeField(verbose_name='updated on')),
                ('notation', models.CharField(max_length=500)),
            ],
        ),
    ]
