# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='incomplete', max_length=20),
            preserve_default=False,
        ),
    ]
