# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160416_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='narrative_as_file',
            field=models.FileField(blank=True, upload_to=projects.models.user_dir_path),
        ),
    ]
