# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160429_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='status',
            field=models.CharField(max_length=60),
        ),
    ]
