# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160503_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='created_date',
            field=models.DateField(verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='completion',
            name='updated_date',
            field=models.DateField(verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_date',
            field=models.DateField(verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateField(verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='updated_date',
            field=models.DateField(verbose_name='updated on'),
        ),
    ]
