# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160504_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='hours',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completion',
            name='created_date',
            field=models.DateTimeField(verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='completion',
            name='updated_date',
            field=models.DateTimeField(verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='updated_date',
            field=models.DateTimeField(verbose_name='updated on'),
        ),
    ]
