#!/bin/bash

clear
echo "Installing the dependencies on OS-side"
sudo apt-get install g++ -y 
sudo apt-get install pandoc -y
sudo apt-get install libxml2-dev libxslt-dev python-dev python3-lxml -y

echo "Installing python environment"
pip install -r requirements.txt

